# mysql:
#   host: '127.0.0.1'
#   port: 3306
#   user: "root"
#   password: "123456"
#   db: 'lushop_inventory_srv'

nacos:
  host: '192.168.226.140'
  port: '8848'
  namespace: '882378fb-1b26-49d4-90c4-51db79108f34'
  user: 'nacos'
  password: 'nacos'
  dataid: 'inventory_srv.json'
  group: 'pro'