pipeline {
    agent any

    stages {
        stage('pull code') {
            steps {
                git credentialsId: 'gitee-user-password', url: 'https://gitee.com/LucienLSA/lushop.git'
            }
        }
        stage('build project') {
            steps {
                sh '''echo "运行 cnpm install"
                    cnpm install
                    echo "运行 cnpm install"
                    cnpm run build
                    echo "构建成功"
                    '''
            }
        }
        stage('build project') {
            steps {
                sshPublisher(publishers: [sshPublisherDesc(configName: '192.168.226.140-root', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: 'echo "success"', execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: 'docker/nginx/data/html', remoteDirectorySDF: false, removePrefix: 'dist', sourceFiles: 'dist/**')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
            }
        }
    }
}
