# name: 'goods_web'
# port: 8033


# goods_srv:
#   name: 'goods_srv'
#   version: 'v1'


# jwt:
#   key: 'lushop_secret_key'
#   expired_time: 2592000

# ali_sms:
#   api_key: 'Ali_ApiKey'
#   api_secret: 'Ali_ApiSecret'
#   sign_name: '阿里云短信测试'
#   template_code: 'SMS_154950909'
#   phone_number: '19821216806'
#   region_id: 'cn-hangzhou'
#   expire: 600

# redis:
#   host: '127.0.0.1'
#   port: '6379'
#   db: 4
#   password: ''
#   pool_size: 10

# consul:
#   host: '192.168.226.140'
#   port: '8500'


nacos:
  host: '192.168.226.140'
  port: '8848'
  namespace: 'd44bc5b3-42e3-4aa1-9ea7-14d6a747880c'
  user: 'nacos'
  password: 'nacos'
  dataid: 'goods_web.json'
  group: 'dev'


