# mysql:
#   host: '127.0.0.1'
#   port: 3306
#   user: "root"
#   password: "123456"
#   db: 'lushop_goods_srv'

nacos:
  host: '192.168.226.140'
  port: '8848'
  namespace: '97b453ea-69de-46f4-a691-7a0e14977f2a'
  user: 'nacos'
  password: 'nacos'
  dataid: 'goods_srv.json'
  group: 'pro'