# mysql:
#   host: '127.0.0.1'
#   port: 3306
#   user: "root"
#   password: "123456"
#   db: 'lushop_user_srv'

nacos:
  host: '192.168.226.140'
  port: '8848'
  namespace: '4da0930f-5769-446a-b916-7195bd731fed'
  user: 'nacos'
  password: 'nacos'
  dataid: 'user_srv.json'
  group: 'pro'